

export const NIVELES = [
  "FOSA DE CABLE",
  "PB",
  "P1",
  "P2",
  "P3",
  "P4",
  "P5",
  "P6",
  "AZOTEA",
  "PERIMETRO INTERNO",
  "PERIMETRO EXTERNO"
];

export const AREAS = [
  "SALA DE BATERIA",
  "CASILLA DE VIGILANCIA",
  "AREA PUBLICA",
  "BAÑO",
  "SALA AA",
  "SALA DE DISTRUBUIDOR",
  "LAVA MOPAS",
  "SALA DE MOTOGENERADORES",
  "DEPOSITO",
  "ESTACIONAMIENTO",
  "ALMACEN",
  "SALA DE RETICFICADORES",
  "SALA DE TRANSMISION",
  "SALA DE ENERGIA",
  "SALA DE AIRES ACONDICIONADOS",
  "BAÑO DE LA CENTRAL",
  "BAÑO DE CASILLA DE VIGILANCIA",
  "SALA PCM",
  "TALLER MECANICO",
  "ESCALERAS",
  "AREA DE CALENTAMIENTO",
  "PASILLOS",
  "SALA DE VIDEO CONFERENCIA",
  "OFICINA DE GESTION HUMANA",
  "AULAS DE CET",
  "OFICINA MANTENIMIENTO Y SERVICIOS",
  "OFICINA TRANSPORTE",
  "CENTRO CONTROL ESTATAL",
  "GERENCIA DE RED",
  "ENTRADA PROVISION",
  "OFICINA DE INSTITUCIONES PUBLICAS",
  "DEPOSITO DE RED",
  "SALA DIGITAL",
  "SALA DE DESCANSO",
  "SALA DE SISTEMAS",
  "ENTRADA PRINCIPAL",
  "ENTRADA DE AHORRO",
  "OFICINA DATOS",
  "OFICINA DE EQUIPOS DE MEDICION",
  "CENTRAL DIGITAL",
  "SALA DE TERCEROS USUARIOS DE FONDO",
  "SALA DE TERCEROS USUARIOS DE ENTRADA",
  "PASILLO FRENTE ESCALERA",
  "PASILLO DIAGONAL ENTRADA AZOTEA",
  "OFICINA PLANTA EXTERNA",
  "SALA ATENCION AL CLIENTE"
];

export const RUBROS = [
  "Actividades de trabajo en caliente",
  "Aguas limpias y servidas",
  "Árboles y vegetación",
  "Área  para consumir alimentos",
  "Ascensor",
  "Baños",
  "Baterías",
  "Cableado Eléctrico",
  "Cableado o dispositivos de Red",
  "Cerca perimetral",
  "Comedores (área preparación alimentos)",
  "Desincorporación de Activos",
  "Detectar gases combustibles en vehículos",
  "Documentación Legal",
  "Emisiones",
  "Equipo de Protección Personal (EPP) / Herramienta de Seguridad (HS)",
  "Escaleras (Edificaciones)",
  "Escaleras (Móviles/Portátiles)",
  "Estacionamientos",
  "Evaluaciones de puestos de trabajo",
  "Extintores",
  "Izaje de carga",
  "Lámpara de Emergencia",
  "Lámpara y bombillos fluorescentes",
  "Medición de dosis de ruido acumuladas",
  "Medición de estrés térmico",
  "Medición del nivel de presión sonora",
  "Medir la iluminancia real",
  "Medir la velocidad del viento",
  "Medir los campos magnéticos",
  "Mobiliario",
  "Orden y Limpieza/Mtto.",
  "Otros",
  "Paralización de Obras",
  "Pared Drywall",
  "Paredes",
  "Periférico Laptop´s",
  "Piso",
  "Plafón",
  "Presencia de Animales (roedores, insectos, aves)",
  "Presencia de gases peligrosos",
  "Primeros Auxilios",
  "Puertas de Emergencia",
  "Puertas/Barandas",
  "Ruido y emisiones de gases",
  "SDAI",
  "Señalización",
  "SFEA",
  "Sillas",
  "Sistemas Contra Incendios",
  "Sistemas de AA - Ventilación",
  "Sustancias Peligrosas",
  "Tableros Eléctricos",
  "Tanque de Combustibles",
  "Tanque subterráneos",
  "Techo",
  "Techo Drywall",
  "Toma-corrientes",
  "Torre - Antenas",
  "Vehículos (Camiones, montacargas, carretillas, grúas)",
  "Ventanas - Vidrios",
  "Vidrios Estación Manual (SDAI)"
];

export const UNIDADES_RESPONSABLES = [
  "Almacenes (GG Servicios y Logística)",
  "Auditoría Interna",
  "Comunicaciones y Asuntos Públicos",
  "Consultoría Jurídica",
  "Empresas e Instituciones Privadas",
  "Energía y Climatización",
  "Finanzas",
  "Fortalecimiento del Poder Popular",
  "Gestión de Flota",
  "Gestión Humana",
  "GSHA (GG Seguridad Integral)",
  "Infraestructura",
  "Instituciones Públicas",
  "Servicios Internos (GGSL)",
  "Mercadeo Corporativo",
  "Mercados Masivos",
  "Oficina de Proyectos Estratégicos",
  "Operaciones Centralizadas",
  "Operadores de Telecomunicaciones",
  "Personal en Asignación",
  "Planificación",
  "Planificación Tecnológica",
  "Presidencia Cantv",
  "Procura",
  "Proyectos Mayores",
  "Recaudación y Pagos",
  "Seguimiento y Control Integral de Gestión",
  "Seguridad Integral",
  "Servicios Masivos (GGMM)",
  "Servicios y Logística",
  "Sistemas",
  "Tecnología y Operaciones",
  "Unidad Prevención Control LCFT",
  "Vicepresidencia Ejecutiva",
  "Vicepresidencia Gestión Interna",
  "Vicepresidencia Prestación de Servicios",
  "Vicepresidencia Tecnología e Infraestructura"
];

export const CRITICIDAD = ["Alta", "Media", "Baja"];

export const STATUS = ["Solventado", "No Solventado", "Operativo", "No Operativo"];