// constants/Localidad.js
export const EMPRESA_CANTV = 'CANTV';

export const CANTV_LOCALIDADES = [
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'CÁRDENAS', parroquia: 'TÁRIBA', sede: 'CENTRAL TÁRIBA' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'PÁEZ', parroquia: 'ACARIGUA', sede: 'Central Acarigua (Edificio Técnico I)' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'CECILIO ACOSTA', sede: 'ALMACÉN NODAL MARACAIBO (COS)' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN CRISTÓBAL', parroquia: 'PEDRO MARÍA MORANTES', sede: 'CENTRAL / PLANTA EXTERNA PIRINEOS' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'TURÉN', parroquia: 'VILLA BRUZUAL', sede: 'Central Digital Turen' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'OLEGARIO VILLA LOBOS', sede: 'CENTRAL BELLA VISTA III' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN CRISTÓBAL', parroquia: 'LA CONCORDIA', sede: 'CENTRAL CONCORDIA (LUCIO OQUENDO)' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'GUANARE', parroquia: 'GUANARE', sede: 'Central Guanare edificio Técnico II)' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'CABIMAS', parroquia: 'LA ROSA', sede: 'CENTRAL CABIMAS CABILLAS' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN CRISTÓBAL', parroquia: 'SAN JUAN BAUTISTA', sede: 'CENTRO OPERATIVO PUEBLO NUEVO (3 EDIFICIOS)' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'GUANARE', parroquia: 'GUANARE', sede: 'Edificio Técnico II' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'CABIMAS', parroquia: 'CARMEN HERRERA', sede: 'CENTRAL CABIMAS CENTRO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'AYACUCHO', parroquia: 'SAN JUAN DE COLÓN', sede: 'CENTRAL COLÓN' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'ARAURE', parroquia: 'ARAURE', sede: 'Móvil Río Acarigua' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'CECILIO ACOSTA', sede: 'CENTRAL CAMPO ALEGRE (COS)' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'JUNÍN', parroquia: 'RUBIO', sede: 'CENTRAL RUBIO' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'PÁEZ', parroquia: 'ACARIGUA', sede: 'OAC Acarigua' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'LAGUNILLAS', parroquia: 'ALONSO DE OJEDA', sede: 'CENTRAL CIUDAD OJEDA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'BOLÍVAR', parroquia: 'SAN ANTONIO DEL TÁCHIRA', sede: 'CENTRAL SAN ANTONIO' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'GUANARE', parroquia: 'GUANARE', sede: 'OAC Guanare' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'COQUIVACOA', sede: 'CENTRAL COQUIVACOA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN CRISTÓBAL', parroquia: 'SAN JUAN BAUTISTA', sede: 'CENTRAL SAN CRISTÓBAL CENTRO' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'MONSEÑOR DE UNDA', parroquia: 'PEÑA BLANCA', sede: 'NODO  PEÑA BLANCA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'CHIQUINQUIRA', sede: 'CENTRAL LAS DELICIAS (MARACAIBO)' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN CRISTÓBAL', parroquia: 'LA CONCORDIA', sede: 'CAI CONCORDIA' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'SUCRE', parroquia: 'BISCUCUY', sede: 'NODO  MESA DE PIÑAL ZORRO (BISCUCUY)' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'JUANA DE AVILA', sede: 'CENTRAL FRONTERAS' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN CRISTÓBAL', parroquia: 'PEDRO MARÍA MORANTES', sede: 'CAI PIRINEOS' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'OSPINO', parroquia: 'LA APARICIÓN', sede: 'NODO  LA APARICION' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'MANUEL DANIGNO', sede: 'CENTRAL INDUSTRIAS' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'JUNÍN', parroquia: 'RUBIO', sede: 'CAI RUBIO' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'GUANARE', parroquia: 'VIRGEN DE LA COROMOTO', sede: 'NODO TUCUPIDO' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'CRISTO DE ARANZA', sede: 'CENTRAL LA LAGO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'JÁUREGUI', parroquia: 'LA GRITA', sede: 'CAI LA GRITA' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'GUANARE', parroquia: 'GUANARE', sede: 'NODO GUANARE' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'RAUL LEONIS', sede: 'CENTRAL LOS OLIVOS' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'AYACUCHO', parroquia: 'SAN JUAN DE COLÓN', sede: 'NODO SAN JUAN DE COLÓN (SALA TX)' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'AGUA BLANCA', parroquia: 'AGUA BLANCA', sede: 'NODO AGUA BLANCA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MACHIQUES DE PERIJA', parroquia: 'LIBERTAD', sede: 'CENTRAL MACHIQUES' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'GARCÍA DE HEVIA', parroquia: 'LA FRÍA', sede: 'NODO LA FRIA' },
  { region: 'Los Llanos', estado: 'PORTUGUESA', municipio: 'ARAURE', parroquia: 'ARAURE', sede: 'NODO ARAURE (ACARIGUA)' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'SAN FRANCISCO', parroquia: 'SAN FRANCISCO', sede: 'CENTRAL SAN FELIPE' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'FERNANDEZ FEO', parroquia: 'SAN ANTONIO DE CAPARO', sede: 'NODO LA PEDRERA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'SAN FRANCISCO', parroquia: 'SAN FRANCISCO', sede: 'CENTRAL SAN FRANCISCO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'FERNANDEZ FEO', parroquia: 'SAN RAFAEL DEL PIÑAL', sede: 'NODO SAN RAFAEL DEL PIÑAL' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'CECILIO ACOSTA', sede: 'CENTRAL SAN MIGUEL' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'PANAMERICANO', parroquia: 'COLONCITO', sede: 'NODO COLONCITO' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'SANTA LUCIA', sede: 'CENTRAL URDANETA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN CRISTÓBAL', parroquia: 'SAN JUAN BAUTISTA', sede: 'CENTRAL PARAMILLO II' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'ROSARIO DE PERIJA', parroquia: 'EL ROSARIO', sede: 'CENTRAL VILLA DEL ROSARIO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'AYACUCHO', parroquia: 'SAN JUAN DE COLÓN', sede: 'CAI COLÓN' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'CECILIO ACOSTA', sede: 'EDIFICIO ADMINISTRATIVO (COS)' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'BOLÍVAR', parroquia: 'SAN ANTONIO DEL TÁCHIRA', sede: 'CADI SAN ANTONIO' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARA', parroquia: 'SAN RAFAEL DEL MOJAN', sede: 'MÓVIL EL MOJAN' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'JUNÍN', parroquia: 'BRAMÓN', sede: 'CASETA TX BRAMÓN' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'CABIMAS', parroquia: 'CARMEN HERRERA', sede: 'CAI CANTV CABIMAS' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'GUASIMOS', parroquia: 'PALMIRA', sede: 'REPETIDORA CERRO GALLINERO' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'LAGUNILLAS', parroquia: 'ALONSO DE OJEDA', sede: 'CAI CANTV CIUDAD OJEDA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAMUEL DARIO MALDONADO', parroquia: 'HERNÁNDEZ', sede: 'CASETA TX SANTA ROSA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'SANTA LUCIA', sede: 'OEP URDANETA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'GARCÍA DE HEVIA', parroquia: 'LA FRÍA', sede: 'CAI LA FRIA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARA', parroquia: 'RICAURTE', sede: 'NODO SANTA CRUZ DE MARA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'LIBERTADOR', parroquia: 'ABEJALES', sede: 'NODO ABEJALES' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARA', parroquia: 'EL MOJAN', sede: 'NODO SAN RAFAEL DEL MOJAN' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'RAFAEL URDANETA', parroquia: 'DELICIAS', sede: 'REPETIDORA MATA MULA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MACHIQUES DE PERIJA', parroquia: 'LA CONCEPCIÓN', sede: 'NODO SAN JOSE DE PERIJA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SUCRE', parroquia: 'QUENIQUEA', sede: 'NODO QUENIQUEA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'ROSARIO DE PERIJA', parroquia: 'SIXTO SAMBRANO', sede: 'NODO SAN IGNACIO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SUCRE', parroquia: 'ELEAZAR LOPEZ CONTRERAS', sede: 'REPETIDORA LOS COLORADOS' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MACHIQUES DE PERIJA', parroquia: 'RIO NEGRO', sede: 'NODO RÍO NEGRO (CAMPO BERNAL)' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'LIBERTADOR', parroquia: 'SAN JOAQUIN DE NAVAY', sede: 'CASETA TX SAN JOAQUIN DE NAVAY' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'JESÚS MARÍA SEMPRUN', parroquia: 'JESÚS MARÍA SEMPRUN', sede: 'NODO CASIGUA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'TORBES', parroquia: 'SAN JOSECITO', sede: 'CASETA TX SAN JOSECITO' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'RAUL LEONIS', sede: 'CAI CANTV LOS OLIVOS' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN CRISTÓBAL', parroquia: 'SAN JUAN BAUTISTA', sede: 'URL LAS LOMAS SANTA TERESA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MARACAIBO', parroquia: 'OLEGARIO VILLA LOBOS', sede: 'CAI CANTV SALTO ÁNGEL' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'URIBANTE', parroquia: 'POTOSÍ', sede: 'CASETA TX SIBERIA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'SAN FRANCISCO', parroquia: 'SAN FRANCISCO', sede: 'CAI CANTV SAN FRANCISCO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN JUDAS TADEO', parroquia: 'UMUQUENA', sede: 'NODO UMUQUENA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'ZAMORA', parroquia: 'PUERTO CUMAREBO', sede: 'CENTRAL CUMAREBO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'FERNANDEZ FEO', parroquia: 'SANTO DOMINGO', sede: 'CASETA TX LOS NARANJOS' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'SILVA', parroquia: 'TUCACAS', sede: 'CENTRAL TUCACAS' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'CORDOVA', parroquia: 'SANTA ANA', sede: 'NODO SANTA ANA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'CARIRUBANA', parroquia: 'CARIRUBANA', sede: 'CENTRO DE TRABAJO JACINTO LARA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'LOBATERA', parroquia: 'CONSTITUCIÓN', sede: 'REPETIDORA LA CORTADA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'MIRANDA', parroquia: 'SAN ANTONIO', sede: 'CENTRAL CORO I' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'LOBATERA', parroquia: 'CONSTITUCIÓN', sede: 'NODO BOROTA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'MIRANDA', parroquia: 'SAN GABRIEL', sede: 'CENTRAL CORO II' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'INDEPENDENCIA', parroquia: 'CAPACHO NUEVO', sede: 'CENTRAL CAPACHO - INDEPENDENCIA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'CARIRUBANA', parroquia: 'CARIRUBANA', sede: 'EDIFICIO EQUIPOS PUNTO FIJO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'LIBERTAD', parroquia: 'CAPACHO VIEJO', sede: 'CASETA TX CERRO EL CRISTO' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'MIRANDA', parroquia: 'SAN ANTONIO', sede: 'CAI CANTV CORO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'CORDOVA', parroquia: 'SANTA ANA', sede: 'CASETA TX CERRO EL TAMBO' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'CARIRUBANA', parroquia: 'CARIRUBANA', sede: 'CAI CANTV PUNTO FIJO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'PEDRO MARIA UREÑA', parroquia: 'NUEVA ARCADIA', sede: 'CENTRAL UREÑA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'MIRANDA', parroquia: 'SANTA ANA', sede: 'TRANSPORTE CORO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'TORBES', parroquia: 'SAN JOSECITO', sede: 'NODO EL COROZO' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'FEDERACION', parroquia: 'CHURUGUARA', sede: 'NODO CHURUGUARA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'JOSÉ MARÍA VARGAS', parroquia: 'EL COBRE', sede: 'REPETIDORA EL ZUMBADOR' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'FEDERACIÓN', parroquia: 'EL PAUJÍ', sede: 'NODO EL PAUJI' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'LIBERTAD', parroquia: 'CIPRIANO CASTRO', sede: 'NODO HATO LA VIRGEN' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'FEDERACION', parroquia: 'AGUA LARGA', sede: 'NODO MARIA DIAZ' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'INDEPENDENCIA', parroquia: 'CAPACHO NUEVO', sede: 'CAPACHO I' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'SUCRE', parroquia: 'SUCRE', sede: 'NODO LA CRUZ DE TARATARA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'CARDENAS', parroquia: 'LA FLORIDA', sede: 'CASETA TX LA FLORIDA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'BOLIVAR', parroquia: 'SAN LUIS', sede: 'NODO LA ENCRUCIJADA (LA VEGA)' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'JOSÉ MARÍA VARGAS', parroquia: 'EL COBRE', sede: 'NODO EL COBRE' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'BOLIVAR', parroquia: 'SAN LUIS', sede: 'NODO SAN LUIS' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'JAUREGUI', parroquia: 'LA GRITA', sede: 'NODO LA GRITA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'BOLIVAR', parroquia: 'SAN LUIS', sede: 'NODO LA CIENAGA - EL DESENGAÑO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'BOLIVAR', parroquia: 'ISAIAS MEDINA ANGARITA', sede: 'CASETA TX LAS DANTAS' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'BOLIVAR', parroquia: 'LA PEÑA', sede: 'NODO LA PEÑA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'RAFAEL URDANETA', parroquia: 'DELICIAS', sede: 'NODO LAS DELICIAS' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'BOLIVAR', parroquia: 'LA PEÑA', sede: 'NODO EL MAMON' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'MICHELENA', parroquia: 'MICHELENA', sede: 'CENTRAL MICHELENA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'MIRANDA', parroquia: 'GUZMAN GUILLERMO', sede: 'NODO LOS QUEMADOS' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'FERNANDEZ FEO', parroquia: 'ALBERTO ADRIANI', sede: 'REPETIDORA RIO FRIO' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'PALAVECINO', parroquia: 'CABUDARE', sede: 'NODO CABURE' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SEBORUCO', parroquia: 'SEBORUCO', sede: 'SAN DIEGO - LOS QUEMADOS' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'CARIRUBANA', parroquia: 'CARIRUBANA', sede: 'NODO PUNTO FIJO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'FRANCISCO DE MIRANDA', parroquia: 'SAN JOSE DE BOLIVAR', sede: 'NODO SAN JOSE DE BOLIVAR' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'FEDERACION', parroquia: 'MAPARARI', sede: 'NODO DUVISI (LA GARZA)' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SEBORUCO', parroquia: 'SEBORUCO', sede: 'NODO SEBORUCO' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'CARIRUBANA', parroquia: 'CARIRUBANA', sede: 'TX CERRO SANTA ANA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN CRISTÓBAL', parroquia: 'SAN SEBASTIAN', sede: 'ZORCA SAN ISIDRO' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'CARIRUBANA', parroquia: 'PUNTA CARDON', sede: 'TX PUNTA CARDON' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'GUASIMOS', parroquia: 'PALMIRA', sede: 'URL PALMIRA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'LOS TAQUES', parroquia: 'LOS TAQUES', sede: 'TX LOS TAQUES' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'CARDENAS', parroquia: 'AMENODORO RANGEL LAMUS', sede: 'URL PALO GORDO' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'LOS TAQUES', parroquia: 'JUDIBANA', sede: 'TX JUDIBANA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'URIBANTE', parroquia: 'PREGONERO', sede: 'NODO PREGONERO' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'FALCON', parroquia: 'PUEBLO NUEVO', sede: 'TX PUEBLO NUEVO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SUCRE', parroquia: 'SAN PABLO', sede: 'CASETA TX SAN PABLO' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'FALCON', parroquia: 'ADICORA', sede: 'TX ADICORA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN JUDAS TADEO', parroquia: 'UMUQUENA', sede: 'LA CUCHILLA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'COLINA', parroquia: 'LA VELA DE CORO', sede: 'NODO LA VELA DE CORO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN CRISTÓBAL', parroquia: 'SAN SEBASTIAN', sede: 'NODO ZORCA PROVIDENCIA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'COLINA', parroquia: 'LAS CALDERAS', sede: 'TX LAS CALDERAS' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'SAN CRISTÓBAL', parroquia: 'SAN JUAN BAUTISTA', sede: 'URL PARAMILLO I' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'MIRANDA', parroquia: 'SAN GABRIEL', sede: 'TX SABANA LARGA' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'ANDRES BELLO', parroquia: 'CORDERO', sede: 'URL CORDERO' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'MIRANDA', parroquia: 'SAN GABRIEL', sede: 'TX CAUJARO' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'URIBANTE', parroquia: 'CARDENAS', sede: 'CASETA TX LA FUNDACIÓN' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'PIRITU', parroquia: 'PIRITU', sede: 'NODO PIRITU' },
  { region: 'Los Andes', estado: 'TÁCHIRA', municipio: 'JAUREGUI', parroquia: 'LA GRITA', sede: 'REPERIDORA BAILADORES' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'TOCOPERO', parroquia: 'TOCOPERO', sede: 'NODO TOCOPERO' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'SAMUEL DARIO MALDONADO', parroquia: 'BOCONÓ', sede: 'NODO BOCONO (TACHIRA)' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'ACOSTAS', parroquia: 'SAN JUAN DE LOS CAYOS', sede: 'TX SAN JUAN DE LOS CAYOS' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'SAMUEL DARIO MALDONADO', parroquia: 'HERNÁNDEZ', sede: 'CASETA TX LAS HERNANDEZ' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'MONSEÑOR ITURRIZA', parroquia: 'CHICHIRIVICHE', sede: 'TX CHICHIRIVICHE' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'SAMUEL DARIO MALDONADO', parroquia: 'LA TENDIDA', sede: 'CASETA TX LA TENDIDA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'PALMA SOLA', parroquia: 'PALMA SOLA', sede: 'NODO PALMA SOLA' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'CAMPO ELIAS', parroquia: 'MATRIZ', sede: 'CENTRAL EJIDO' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'SILVA', parroquia: 'BOCA DE AROA', sede: 'TX BOCA DE AROA' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'ALBERTO ADRIANI', parroquia: 'PRESIDENTE PAEZ', sede: 'CENTRAL EL VIGÍA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'SAN FRANCISCO', parroquia: 'MIRIMIRE', sede: 'NODO MIRIMIRE' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'LIBERTADOR', parroquia: 'OSUNA RODRÍGUEZ', sede: 'CENTRAL LA PUNTA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'JAURA', parroquia: 'JACURA', sede: 'NODO JACURA' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'LIBERTADOR', parroquia: 'SAGRARIO', sede: 'CENTRAL MÉRIDA I' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'PETROLERA', parroquia: 'PUEBLO NUEVO DE LA SIERRA', sede: 'TX PUEBLO NUEVO DE LA SIERRA' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'LIBERTADOR', parroquia: 'SAGRARIO', sede: 'CENTRAL MÉRIDA II' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'UNION', parroquia: 'SANTA CRUZ DE BUCARAL', sede: 'TX SANTA CRUZ DE BUCARAL' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'LIBERTADOR', parroquia: 'LASSO DE LA VEGA', sede: 'CENTRAL PEDREGOSA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'DABAJURO', parroquia: 'DABAJURO', sede: 'TX DABAJURO' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'LIBERTADOR', parroquia: 'SAGRARIO', sede: 'CAI MÉRIDA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'BUCHIVACOA', parroquia: 'CAPATARIDA', sede: 'TX CAPATARIDA' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'LIBERTADOR', parroquia: 'SAGRARIO', sede: 'CENTRO OPERATIVO Y SERVICIO MÉRIDA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'MAUROA', parroquia: 'MENE DE MAUROA', sede: 'TX MENE DE MAUROA' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'ALBERTO ADRIANI', parroquia: 'PRESIDENTE PAEZ', sede: 'CAI EL VIGIA' },
  { region: 'Occidente', estado: 'FALCÓN', municipio: 'URUMACO', parroquia: 'URUMACO', sede: 'TX URUMACO' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'ALBERTO ADRIANI', parroquia: 'PRESIDENTE PAEZ', sede: 'COS EL VIGIA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'CONCEPCION', sede: 'ALMACEN LARA (COS BARQUISIMETO)' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'LIBERTADOR', parroquia: 'ARIAS', sede: 'NODO VALLECITO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'CATEDRAL', sede: 'CENTRAL BARQUISIMETO CENTRO (LARA)' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'LIBERTADOR', parroquia: 'GONZALO PICÓN FEBRES', sede: 'NODO EL VALLE' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'CONCEPCIÓN', sede: 'CENTRAL OBELISCO' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'LIBERTADOR', parroquia: 'SAGRARIO', sede: 'REPETIDORA EL MORRO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'PALAVECINO', parroquia: 'CABUDARE', sede: 'CENTRAL CABUDARE' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'SUCRE', parroquia: 'SAN JUAN', sede: 'NODO LAGUNILLAS' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'SANTA ROSA', sede: 'CENTRAL CAMORUCO' },
  { region: 'Los Andes', estado: 'MÉRIDA', municipio: 'RIVAS DÁVILA', parroquia: 'BAILADORES', sede: 'NODO BAILADORES' },
  { region: 'Occidente', estado: 'LARA', municipio: 'TORRES', parroquia: 'TRINIDAD SAMUEL', sede: 'CENTRAL CARORA' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'TRUJILLO', parroquia: 'CHIQUINQUIRÁ', sede: 'CENTRAL TRUJILLO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'CATEDRAL', sede: 'CENTRAL ESTE' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'VALERA', parroquia: 'MERCEDES DÍAZ', sede: 'CENTRAL VALERA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'UNION', sede: 'CENTRAL INDUSTRIAL' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'BOCONÓ', parroquia: 'BOCONÓ', sede: 'CENTRAL BOCONÓ' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'JUAN DE VILLEGAS', sede: 'CENTRAL METROPOLITANO' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'SUCRE', parroquia: 'SABANA DE MENDOZA', sede: 'NODO SABANA DE MENDOZA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'TAMACA', sede: 'CENTRAL TAMACA' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'TRUJILLO', parroquia: 'CHIQUINQUIRÁ', sede: 'CAI TRUJILLO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'CONCEPCION', sede: 'COS BARQUISIMETO' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'VALERA', parroquia: 'MERCEDES DÍAZ', sede: 'CAI VALERA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'SANTA ROSA', sede: 'EDIFICIO ADMINISTRATIVO LARA (LOS LEONES)' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'BOCONÓ', parroquia: 'BOCONÓ', sede: 'CAI BOCONÓ' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'SANTA ROSA', sede: 'CAI LOS LEONES' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'VALERA', parroquia: 'MERCEDES DÍAZ', sede: 'CENTRO OPERATIVO Y SERVICIO VALERA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'CONCEPCIÓN', sede: 'CAI OBELISCO' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'PAMPANITO', parroquia: 'PAMPANITO', sede: 'NODO PAMPANITO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'TORRES', parroquia: 'TRINIDAD SAMUEL', sede: 'CAI CARORA' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'CARVAJAL', parroquia: 'CARVAJAL', sede: 'NODO CARVAJAL' },
  { region: 'Occidente', estado: 'LARA', municipio: 'PALAVECINO', parroquia: 'CABUDARE', sede: 'CAI CABUDARE' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'PAMPÁN', parroquia: 'PAMPÁN', sede: 'NODO PAMPÁN' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'SANTA ROSA', sede: 'OAC LAS TRINITARIAS' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'CANDELARIA', parroquia: 'CHEJENDÉ', sede: 'NODO CHEJENDÉ' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'SANTA ROSA', sede: 'NODO LARA' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'CARACHE', parroquia: 'CARACHE', sede: 'NODO CARACHE' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'SANTA ROSA', sede: 'NODO TIERRA NEGRA' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'RAFAEL RANGEL', parroquia: 'BETIJOQUE', sede: 'NODO BETIJOQUE' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'SANTA ROSA', sede: 'NODO YACAMBU' },
  { region: 'Los Andes', estado: 'TRUJILLO', municipio: 'ESCUQUE', parroquia: 'ESCUQUE', sede: 'NODO ESCUQUE' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'SANTA ROSA', sede: 'NODO EL UJANO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'CATEDRAL', sede: 'NODO LOS CRISTALES' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'CATEDRAL', sede: 'NODO EL MANZANO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'CONCEPCION', sede: 'NODO LA CONCEPCION' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'CONCEPCION', sede: 'NODO CERRITOS BLANCOS' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'CONCEPCION', sede: 'NODO RIO CLARO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'JUAN DE VILLEGAS', sede: 'NODO LA PASTORA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'JUAN DE VILLEGAS', sede: 'NODO LOMAS DE LEON' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'JUAN DE VILLEGAS', sede: 'NODO RUIZ PINEDA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'JUAN DE VILLEGAS', sede: 'NODO CBO PAEZ' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'JUAN DE VILLEGAS', sede: 'NODO EL CARIBE' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'JUAN DE VILLEGAS', sede: 'NODO LA LUCHA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'JUAN DE VILLEGAS', sede: 'NODO 12 DE OCTUBRE' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'TAMACA', sede: 'NODO EL CORDERO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'TAMACA', sede: 'NODO ALÍ PRIMERA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'TAMACA', sede: 'NODO CULEBRA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'TAMACA', sede: 'NODO TAMACA CENTRO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'TAMACA', sede: 'NODO LOMAS VERDES' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'TAMACA', sede: 'NODO RETÉN ABAJO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'EL CUJÍ', sede: 'NODO EL CUJI' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'EL CUJÍ', sede: 'NODO CARORITA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'UNION', sede: 'NODO SAN JACINTO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'UNION', sede: 'NODO BARRIO UNION' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'UNION', sede: 'NODO RIO BARRAGAN' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'BOBADA', sede: 'NODO BOBADA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'IRIBARREN', parroquia: 'AGUEDO FELIPE ALVARADO', sede: 'NODO BOBARU' },
  { region: 'Occidente', estado: 'LARA', municipio: 'PALAVECINO', parroquia: 'CABUDARE', sede: 'NODO LA MATICA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'PALAVECINO', parroquia: 'CABUDARE', sede: 'NODO LOS PENSIONADOS' },
  { region: 'Occidente', estado: 'LARA', municipio: 'PALAVECINO', parroquia: 'CABUDARE', sede: 'NODO LA RIBEREÑA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'PALAVECINO', parroquia: 'JOSE GREGORIO BASTIDAS', sede: 'NODO LOS RANGELES' },
  { region: 'Occidente', estado: 'LARA', municipio: 'PALAVECINO', parroquia: 'JOSE GREGORIO BASTIDAS', sede: 'NODO LA MENDERA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'PALAVECINO', parroquia: 'JOSE GREGORIO BASTIDAS', sede: 'NODO EL TOCUYO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'PALAVECINO', parroquia: 'JOSE GREGORIO BASTIDAS', sede: 'NODO LOS CEDROS' },
  { region: 'Occidente', estado: 'LARA', municipio: 'PALAVECINO', parroquia: 'AGUA VIVA', sede: 'NODO AGUA VIVA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'TORRES', parroquia: 'TRINIDAD SAMUEL', sede: 'NODO CARORA CENTRO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'TORRES', parroquia: 'TRINIDAD SAMUEL', sede: 'NODO LA BANQUERA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'TORRES', parroquia: 'TRINIDAD SAMUEL', sede: 'NODO AREGUE' },
  { region: 'Occidente', estado: 'LARA', municipio: 'TORRES', parroquia: 'TORRES', sede: 'NODO ATARIGUA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'TORRES', parroquia: 'MONTAÑA VERDE', sede: 'NODO MONTAÑA VERDE' },
  { region: 'Occidente', estado: 'LARA', municipio: 'TORRES', parroquia: 'HERIBERTO ARROYO', sede: 'NODO EL EMPALME' },
  { region: 'Occidente', estado: 'LARA', municipio: 'TORRES', parroquia: 'LARA', sede: 'NODO SAN PEDRO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'TORRES', parroquia: 'ALTAGRACIA', sede: 'NODO ALTAGRACIA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'MORAN', parroquia: 'BOLIVAR', sede: 'NODO EL TOCUYO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'MORAN', parroquia: 'GUARICO', sede: 'NODO GUARICO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'MORAN', parroquia: 'HUMOCARO ALTO', sede: 'NODO HUMOCARO ALTO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'MORAN', parroquia: 'HUMOCARO BAJO', sede: 'NODO HUMOCARO BAJO' },
  { region: 'Occidente', estado: 'LARA', municipio: 'MORAN', parroquia: 'ANZOATEGUI', sede: 'NODO ANZOATEGUI' },
  { region: 'Occidente', estado: 'LARA', municipio: 'JIMENEZ', parroquia: 'JUAN BAUTISTA RODRIGUEZ', sede: 'NODO QUIBOR' },
  { region: 'Occidente', estado: 'LARA', municipio: 'JIMENEZ', parroquia: 'CUARA', sede: 'NODO CUARA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'JIMENEZ', parroquia: 'DIEGO DE LOZADA', sede: 'NODO SANARE' },
  { region: 'Occidente', estado: 'LARA', municipio: 'CRESPO', parroquia: 'FREITEZ', sede: 'NODO DUACA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'CRESPO', parroquia: 'JOSE MARIA BLANCO', sede: 'NODO EL ENEAL' },
  { region: 'Occidente', estado: 'LARA', municipio: 'URDANETA', parroquia: 'SIQUISIQUE', sede: 'NODO SIQUISIQUE' },
  { region: 'Occidente', estado: 'LARA', municipio: 'URDANETA', parroquia: 'XAGUAS', sede: 'NODO BARAGUA' },
  { region: 'Occidente', estado: 'LARA', municipio: 'SIMON PLANAS', parroquia: 'SARARE', sede: 'NODO SARARE' },
  { region: 'Occidente', estado: 'LARA', municipio: 'SIMON PLANAS', parroquia: 'GUSTAVO VEGAS LEON', sede: 'NODO LA MIEL' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'COLON', parroquia: 'SAN CARLOS DEL ZULIA', sede: 'CENTRAL SANTA BARBARA DEL ZULIA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'LAGUNILLAS', parroquia: 'VENEZUELA', sede: 'CENTRAL LAGUNILLAS' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'BARALT', parroquia: 'MANUEL GUANIPA MATOS', sede: 'CENTRAL EL VENADO' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'BARALT', parroquia: 'URDANETA', sede: 'CENTRAL MENE GRANDE' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'MIRANDA', parroquia: 'ALTAGRACIA', sede: 'CENTRAL LOS PUERTOS DE ALTAGRACIA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'VALMORE RODRIGUEZ', parroquia: 'LA VICTORIA', sede: 'CENTRAL BACHAQUERO' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'CABIMAS', parroquia: 'PUNTA GORDA', sede: 'CENTRAL PUNTA GORDA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'SANTA RITA', parroquia: 'SANTA RITA', sede: 'CENTRAL SANTA RITA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'GUAJIRA', parroquia: 'GUAJIRA', sede: 'CENTRAL PARAGUAIPOA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'COLON', parroquia: 'MORALITO', sede: 'TX EL MORALITO' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'JESUS MARIA SEMPRUN', parroquia: 'JESUS MARIA SEMPRUN', sede: 'CENTRAL CASIGUA EL CUBO' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'COLON', parroquia: 'SAN CARLOS DEL ZULIA', sede: 'CENTRAL SANTA CRUZ DEL ZULIA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'LAGUNILLAS', parroquia: 'ALONSO DE OJEDA', sede: 'CENTRAL UNION OJEDA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'CATATUMBO', parroquia: 'UDON PEREZ', sede: 'CENTRAL EL GUAYABO' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'SUCRE', parroquia: 'ROMULO GALLEGOS', sede: 'CENTRAL GIBRALTAL' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'LA CAÑADA DE URDANETA', parroquia: 'LA CONCEPCION', sede: 'CENTRAL LA CONCEPCION - LA CAÑADA' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'BOLIVAR', parroquia: 'TAMARE', sede: 'CENTRAL TAMARE' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'SUCRE', parroquia: 'ROMULO GALLEGOS', sede: 'CENTRAL EL BATEY' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'CABIMAS', parroquia: 'GERMAN RIOS LINARES', sede: 'URL LOS LAURELES CABIMAS' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'CABIMAS', parroquia: 'AMBROSIO', sede: 'URL NUEVA DELICIAS CABIMAS' },
  { region: 'Occidente', estado: 'ZULIA', municipio: 'COLON', parroquia: 'SANTA BARBARA', sede: 'CAI SANTA BARBARA' }
];

// 1. Obtener lista de Regiones únicas
export const getRegiones = () => {
  return [...new Set(CANTV_LOCALIDADES.map(item => item.region))].sort();
};

// 2. Obtener Estados por Región
export const getEstadosPorRegion = (region) => {
  if (!region) return [];
  const filtrados = CANTV_LOCALIDADES.filter(item => item.region === region);
  return [...new Set(filtrados.map(item => item.estado))].sort();
};

// 3. Obtener Municipios por Región y Estado
export const getMunicipiosPorEstado = (region, estado) => {
  if (!region || !estado) return [];
  const filtrados = CANTV_LOCALIDADES.filter(
    item => item.region === region && item.estado === estado
  );
  return [...new Set(filtrados.map(item => item.municipio))].sort();
};

// 4. Obtener Parroquias por Municipio
export const getParroquiasPorMunicipio = (region, estado, municipio) => {
  if (!region || !estado || !municipio) return [];
  const filtrados = CANTV_LOCALIDADES.filter(
    item => 
      item.region === region && 
      item.estado === estado && 
      item.municipio === municipio
  );
  return [...new Set(filtrados.map(item => item.parroquia))].sort();
};

// 5. Obtener Instalaciones (Sedes) por Parroquia
export const getInstalacionesPorParroquia = (region, estado, municipio, parroquia) => {
  if (!region || !estado || !municipio || !parroquia) return [];
  const filtrados = CANTV_LOCALIDADES.filter(
    item => 
      item.region === region && 
      item.estado === estado && 
      item.municipio === municipio &&
      item.parroquia === parroquia
  );
  // Mapea directamente a item.sede y extrae valores únicos
  return [...new Set(filtrados.map(item => item.sede))].sort();
};